### PR TITLE
Fixing power in parsing

### LINKED ISSUE #35: Power data errors
Screenshot 2024-11-17 at 10 25 24

### PR DESCRIPTION
**Pull request by samsmithnz**
fixes #35

### CODE REVIEW

**Comment by samsmithnz** [comment]
This fixes the data. Cast Screws and Silica are now 4MW, Refineries are 30MW, etc. 

Now working on verifying in tests that the power requirements are correct. This could be a bit of chicken and egg.

**Comment by samsmithnz** [comment]
The mock tests aren't sufficient here. We need integration tests, where we setup the factory, and then calculate the power + ingredients and confirm they are what we expect. Will revisit tomorrow.

**Comment by Maelstromeous** [comment]
@samsmithnz  I'm basically working on exactly that in my meaty PR

**Comment by Maelstromeous** [comment]
Check out web/src/utils/factory-setups/template.spec.ts in that PR and I think that's basically what you're after. If you'd like you don't need to wait for my PR to go in, you can add your own factory setup exactly how you want it and test that.

**Comment by samsmithnz** [comment]
Is the game-data cached in cloudflare? When I was trying to run the web locally, it wasn't using the local game-data, and I wasn't sure why. It made testing hard.

**Comment by Maelstromeous** [comment]
> Is the game-data cached in cloudflare? When I was trying to run the web locally, it wasn't using the local game-data, and I wasn't sure why. It made testing hard.

It is but the version name change makes it re-download.

The reason is because the game data wasn't actually in the web folder, I've done the changes needed and updated the readme for next time.

**Comment by samsmithnz** [comment]
ok. This is ready to merge, with a review/approval/blessing/sacrifice/whatever you need.

**Comment by Maelstromeous** [comment]
Also I've just realised that we should be rounding the power to the ceil of a whole building. E.g. in the oil recipe we technically use 23.x refineries, we probably should be providing power for 24x refineries, **or** we just leave it until we do the overclocking pass cos that will need to take a lot more math into the power calculations.

**Review by Maelstromeous — CHANGES_REQUESTED** [review]
See testing

**Comment by samsmithnz** [comment]
> Also I've just realised that we should be rounding the power to the ceil of a whole building. E.g. in the oil recipe we technically use 23.x refineries, we probably should be providing power for 24x refineries, **or** we just leave it until we do the overclocking pass cos that will need to take a lot more math into the power calculations.

I assumed that if the buildings required is 11.5 - that means we are underclocking the 12th building...

**Comment by samsmithnz** [comment]
> * FAIL Oil Refinery 400 plastic, 133.333 fuel (24 refineries)
>   
>   * Expected: 697.021MW
>   * Result: 1400MW (way off)
>   * Observed that for plastic the power is set to 60MW??
> 
> ```json
> "building": {
>   "name": "oilrefinery",
>    "power": 60 <<< should be 40
>  },
> ```
> 

Investigating. This is an interesting one.

**Comment by samsmithnz** [comment]
Ok - fixed. Simplified the calculation even more. Tell me if I'm missing something - because I do think it's a 1:1 `if building is constructor, power =4MW, if building is refinery, power =30MW". Note that Quantum Encoder and Particle Accelerator are way off - but I consider this a different bug with the sliding power usage that IS recipe based in many cases.

**Comment by samsmithnz** [comment]
Once this is approved and merged - I assume I can start to integrate in the new tests, and then focus on the variable power buildings. I have some ideas!

**Comment by Maelstromeous** [comment]
> because I do think it's a 1:1 `if building is constructor, power =4MW, if building is refinery, power =30MW".

I think it's literally just as simple as `X buildings * powerPerBuilding`, I'm kinda seeing less and less of a point of putting the power in the recipe, the only benefit I could see us of doing that is when we're using scalar power like quantum encoders / particle acellerators, but I need more of an understanding of how power scales with those.

**Comment by samsmithnz** [comment]
> I'm kinda seeing less and less of a point of putting the power in the recipe, the only benefit I could see us of doing that is when we're using scalar power like quantum encoders / particle acellerators, but I need more of an understanding of how power scales with those.

I agree - but with the recipe based power requirements coming next - it makes sense to leave it there so we are all looking at the same numbers!

**Comment by samsmithnz** [comment]
> @samsmithnz you didn't update the website's copy of the gameData, check the readme on how to do this.

@Maelstromeous I don't see anything in the readme about this? What have I missed? https://github.com/satisfactory-factories/application/blob/main/README.md

**Comment by Maelstromeous** [comment]
> > @samsmithnz you didn't update the website's copy of the gameData, check the readme on how to do this.
> 
> @Maelstromeous I don't see anything in the readme about this? What have I missed? https://github.com/satisfactory-factories/application/blob/main/README.md

Readme.md on your branch :)

**Comment by samsmithnz** [comment]
Ahh - sneaky update to the readme I missed this morning. I think I've done it right! We should automate that copy too, creating an issue if we haven't already. Why is it that every update seems to create 2-3 more tasks? 😂

**Comment by Maelstromeous** [comment]
Depends whether we want to spend the time to do this, as the game data should seldom change. For the sake of a 1 minute copy paste rename job we could spend a solid hour trying to automate it and make it change files. Could do it via `sed` but, yeah, pain.

**Review by Maelstromeous — APPROVED** [review]

**Pull request merged**
