### PR TITLE
Mobile optimisation

### LINKED ISSUE #82: Mobile optimisation
image

Site does not look great on mobile at all 🥲

### PR DESCRIPTION
**Pull request by nils-keller-dev**
Work towards #82 

Not perfect yet but usable
You need to reload the page after switching to mobile if you started off in desktop mode, otherwise the left tray will be broken

### CODE REVIEW

**Comment by Maelstromeous** [comment]
Needs further work it seems https://i.imgur.com/atcor0R.png

**Comment by Maelstromeous** [comment]
Product quantity is obscured, ideally should just be put on a 3rd row https://i.imgur.com/Wdx9dNy.png

**Comment by Maelstromeous** [comment]
Satisfaction looks a bit odd, may be worth to move the buttons below the item https://i.imgur.com/TRn3xtc.png

**Review by Maelstromeous — CHANGES_REQUESTED** [review]
Would still need some optimisation but as you say usable after the above is fixed!

**Comment by nils-keller-dev** [comment]
> Product quantity is obscured, ideally should just be put on a 3rd row https://i.imgur.com/Wdx9dNy.png

Which mobile device is this/what are the dimensions? For me it looks fine even on the smaller phones

**Comment by Maelstromeous** [comment]
> > Product quantity is obscured, ideally should just be put on a 3rd row https://i.imgur.com/Wdx9dNy.png
> 
> Which mobile device is this/what are the dimensions? For me it looks fine even on the smaller phones

https://i.imgur.com/JpR9SsI.png iPhone 11 firefox

**Comment by Maelstromeous** [comment]
Iphone 13: https://i.imgur.com/PBHk7HY.png

**Comment by nils-keller-dev** [comment]
> Iphone 13: https://i.imgur.com/PBHk7HY.png

Two devices I cannot natively select in Chrome 🤔 
I moved the input a row down

**Comment by Maelstromeous** [comment]
Imports at say 600px looks super wonky in comparison to Products https://i.imgur.com/8XCQ7d0.png

**Comment by Maelstromeous** [comment]
While possibly this is out of scope but 800px import qty looks strange https://i.imgur.com/wIfsPID.png

**Comment by nils-keller-dev** [comment]
> While possibly this is out of scope but 800px import qty looks strange https://i.imgur.com/wIfsPID.png

Let's not go down that rabbit hole (for now)

**Comment by Maelstromeous** [comment]
> > Imports at say 600px looks super wonky in comparison to Products https://i.imgur.com/8XCQ7d0.png
> 
> Does this still happen after my latest commit?

After 500px it goes a bit wonky but it's fine for now.

**Comment by Maelstromeous** [comment]
Ok looks good, could we the tray a bit wider? I think 200px is quite small, could we make it 90% or 300px

**Comment by nils-keller-dev** [comment]
> Ok looks good, could we the tray a bit wider? I think 260px is quite small, could we make it 90vw or 300px?

I set it to 300, as relative values sadly didn't seem to work

**Pull request merged**
